site_name: UN Open GIS Initiative DWG7 - Documentation
repo_url: https://github.com/UNopenGIS/7-docs
repo_name: UNopenGIS/7-docs
docs_dir: docs/en
site_dir: site/

theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode  
  font:
    text: Roboto, sans-serif
  language: en
  favicon: etc/media/favicon.png
  logo: etc/media/favicon.png
  name: material
  custom_dir: overrides
  features:
      - content.code.copy
      - content.tabs.link
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
      - content.code.annotate
      - search.highlight
      - toc.follow
      - navigation.indexes
      - navigation.top
      - search.suggest
      
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: octicons/question-16 
      quiz: material/thought-bubble
extra:
  alternate:
    - name: 日本語
      url: https://unopengis.github.io/7-docs/ja/
      lang: ja
    - name: English
      url: https://unopengis.github.io/7-docs/
      lang: en
markdown_extensions:
    - codehilite
    - pymdownx.critic
    - pymdownx.mark
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.magiclink
    - pymdownx.details
    - smarty
    - footnotes
    - meta
    - pymdownx.keys
    # - toc:
    #     permalink: True
    #     toc_depth: 3
    - sane_lists
    - admonition
    - footnotes
    - attr_list
    
extra_javascript:
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - etc/js/tables.js
  - etc/js/extra.js
extra_css:
  - etc/css/extra.css

edit_uri: edit/main/docs/
plugins:
  - git-revision-date
  # - autorefs
  - table-reader
  - tags
  - awesome-pages:
      collapse_single_pages: true
  - macros
  - search:
      lang: en

  # - htmlproofer
      # raise_error: True
