name: Deploy Documentation 
on:
  push:
    branches: 
      - main
  workflow_dispatch:

  
jobs:
  deploy-documentation:
      runs-on: ubuntu-latest
      name: Deploy Documentation to GitHub Pages
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: yarn
            cache-dependency-path: "./package.json"
        - name: 🔎 Check for change in docs folder
          id: changed-documentation
          uses: tj-actions/changed-files@v35
          with:
            files: docs, blog, i18n, docusaurus.config.js, sidebars.js, package.json, yarn.lock, src
        - name: Install dependencies
          if: steps.changed-documentation.outputs.files_changed == 'true'
          working-directory: ./
          run: yarn install
        - name: Build website
          if: steps.changed-documentation.outputs.files_changed == 'true'
          working-directory: ./
          run: yarn build
        - name: Deploy Documentation to GitHub Pages
          if: steps.changed-documentation.outputs.files_changed == 'true'
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
            publish_dir: ./build
            publish_branch: gh-pages
            user_name: github-actions[bot]
            user_email: 41898282+github-actions[bot]@users.noreply.github.com
      # - run: mkdocs gh-deploy --force --dirty
env:
  GH_TOKEN: ${{secrets.GH_ACTIONS_TOKEN}}
