name: Update Events
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    container:
      image: lacmta/geodb-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Run script
        run: python .scripts/events_updater.py
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
        working-directory: ${{ github.workspace }}
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "[Auto] Update events"
          git push
        working-directory: ${{ github.workspace }}