name: Update Events
on:
    schedule:
        - cron: '0 0 * * *'  # Runs every day at 00:00 UTC

jobs:
    update-events:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run script
              run: python ./scripts/events_updater.py  # Replace with the path to your script