name: Update Events
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    container:
      image: lacmta/geodb-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Run script
        run: python .scripts/events_updater.py
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "[Auto] Update events"