name: Update Events
on:
    schedule:
        - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
    workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    container:
      image: lacmta/geodb-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Install Git
        run: apt-get update && apt-get install -y git
      - name: Run script
        run: python .scripts/events_updater.py
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "[Auto] Update events"
          git push