name: Update Events
on:
    schedule:
        - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
    workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Run script
        run: python .scripts/events_updater.py